#---------------TAG-block---------------------
ARG TAG=""
#---------------ARG-block---------------------

#---------------Static-block-1----------------
FROM ${CONTENTIMAGE1:-scratch} as content1
FROM ${CONTENTIMAGE2:-scratch} as content2
FROM ${INITIMAGE:-${BASEIMAGE:-huggla/base:$TAG}} as init
FROM ${BUILDIMAGE:-huggla/build:$TAG} as build
FROM ${BASEIMAGE:-huggla/base:$TAG} as image
COPY --from=build /imagefs /
#---------------RUN-block---------------------

#---------------ENV-block---------------------

#---------------Static-block-2----------------
USER starter
ONBUILD USER root
#---------------End-block---------------------
